version: "3"

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: example
  
  adminer:
    image: adminer
    restart: always
 
  web:
    image: fernandoj17/docker-personalizado:latest
    deploy:
      replicas: 1
    depends_on:
      - db
    ports:
      - "4500:97"
    networks:
      - webnet


networks:
  webnet:

